version: '3'

services:
  graph-microservice:
    build: ./graph-microservice
    volumes:
      - ./graph-microservice/App:/usr/src
    ports:
      - 4000:4000
  draw-microservice:
    build: ./draw-microservice
    volumes:
      - ./draw-microservice:/usr/src
    ports:
      - 3000:3000